# Generated by Django 5.2.17 on 2026-08-25 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scrutin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCAResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinate_1', models.FloatField()),
                ('coordinate_2', models.FloatField()),
                ('coordinate_3', models.FloatField()),
                ('coordinate_4', models.FloatField()),
                ('coordinate_5', models.FloatField()),
                ('coordinate_6', models.FloatField()),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrutin.commune')),
            ],
        ),
    ]
