# Generated by Django 5.2.17 on 2026-09-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_statique', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagestatique',
            options={'ordering': ['ordre', 'titre']},
        ),
        migrations.AddField(
            model_name='pagestatique',
            name='ordre',
            field=models.IntegerField(default=0, help_text="Ordre d'affichage dans le menu."),
        ),
    ]
