# Generated by Django 5.2.17 on 2026-08-29 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('abreviation', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='SujetVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=500)),
                ('sujet_id', models.IntegerField(default=1)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('numero_ofs', models.IntegerField()),
                ('canton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrutin.canton')),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('numero_ofs', models.IntegerField(db_index=True, default=0)),
                ('est_valide', models.BooleanField(default=True)),
                ('langue', models.CharField(max_length=20, null=True)),
                ('degre_urbanisation', models.CharField(max_length=50, null=True)),
                ('nb_voix', models.IntegerField(default=0)),
                ('canton', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='scrutin.canton')),
                ('district', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='scrutin.district')),
            ],
        ),
        migrations.CreateModel(
            name='ResultatCommunalHistorique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_oui', models.IntegerField()),
                ('nombre_non', models.IntegerField()),
                ('electeurs_inscrits', models.IntegerField()),
                ('bulletins_rentres', models.IntegerField()),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrutin.commune')),
                ('sujet_vote', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scrutin.sujetvote')),
            ],
        ),
        migrations.CreateModel(
            name='ResultatCommunalEnCours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_oui', models.IntegerField(null=True)),
                ('nombre_non', models.IntegerField(null=True)),
                ('electeurs_inscrits', models.IntegerField(null=True)),
                ('bulletins_rentres', models.IntegerField(null=True)),
                ('electeur_election_precedente', models.IntegerField()),
                ('comptabilise', models.BooleanField(default=False)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrutin.commune')),
                ('sujet_vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrutin.sujetvote')),
            ],
        ),
        migrations.CreateModel(
            name='Extrapolation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pourcentage_oui_connu', models.FloatField()),
                ('pourcentage_oui_extrapole', models.FloatField()),
                ('avance', models.FloatField()),
                ('moment_creation', models.DateTimeField(auto_now_add=True)),
                ('sujet_vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrutin.sujetvote')),
            ],
        ),
    ]
