# Generated by Django 5.2.17 on 2026-10-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrutin', '0002_resultatcommunalencours_une_ligne_par_commune_et_objet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fourchette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avance', models.FloatField(unique=True)),
                ('demi_largeur', models.FloatField()),
            ],
        ),
    ]
