# Generated by Django 5.2.17 on 2026-10-04 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrutin', '0003_fourchette'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomalie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('niveau', models.CharField(choices=[('vert', 'vert'), ('orange', 'orange'), ('rouge', 'rouge')], max_length=6)),
                ('motifs', models.JSONField(default=list)),
                ('chi2', models.FloatField()),
                ('chi2_corrige', models.FloatField(null=True)),
                ('correction', models.JSONField(null=True)),
                ('ecart_bulletins', models.FloatField(default=0)),
                ('bulletins_habituel', models.FloatField(null=True)),
                ('objets', models.JSONField()),
                ('voisines', models.JSONField(default=list)),
                ('centre', models.JSONField(null=True)),
                ('historique', models.JSONField(null=True)),
                ('signalee_depuis', models.DateTimeField(null=True)),
                ('note', models.TextField(blank=True)),
                ('mise_a_jour', models.DateTimeField()),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrutin.commune')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('date', 'commune'), name='une_anomalie_par_commune')],
            },
        ),
    ]
