"""
Django settings for election project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Configuration locale, non versionnée (voir .env.example).
load_dotenv(BASE_DIR / ".env")


def env_bool(nom, defaut=False):
    valeur = os.environ.get(nom)
    if valeur is None:
        return defaut
    return valeur.strip().lower() in {"1", "true", "yes", "oui"}


DEBUG = env_bool("DEBUG", False)

# En dev on veut un clone qui démarre sans configuration ; en production
# l'absence de clé doit être une erreur bruyante.
SECRET_KEY = os.environ.get("SECRET_KEY")
if not SECRET_KEY:
    if not DEBUG:
        raise RuntimeError(
            "SECRET_KEY manquant. Définissez-le dans .env ou dans "
            "l'environnement (voir .env.example)."
        )
    SECRET_KEY = "django-insecure-cle-de-developpement-uniquement"

ALLOWED_HOSTS = [
    hote.strip()
    for hote in os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if hote.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "scrutin",
    "pca",
    "page_statique",
    "carte"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'election.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'page_statique.context_processors.menu',
            ],
        },
    },
]

WSGI_APPLICATION = 'election.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases


# SQLite partout, dev comme production : un seul écrivain (le pipeline du jour
# J), ~120 000 lignes, et les lectures sont servies par le cache/mirroir
# statique. La sauvegarde est une copie du fichier.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.environ.get("DB_PATH", BASE_DIR / "votation.sqlite3"),
        'OPTIONS': {
            # WAL : lectures concurrentes pendant que le pipeline écrit.
            'init_command': "PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL;",
            'timeout': 20,
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


DEFAULT_AUTO_FIELD='django.db.models.AutoField' 

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Journalisation : les scripts du pipeline parlent via ``logging`` ; sans
# handler sur la racine, Python n'affiche que WARNING et plus, et les messages
# d'avancement du jour J (INFO) seraient perdus.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {'format': '{asctime} {levelname} {name}: {message}', 'style': '{'},
    },
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'formatter': 'simple'},
    },
    'root': {'handlers': ['console'], 'level': 'INFO'},
}
