// Fiches développées des objets qui définissent les axes (annexe A).
// Les chiffres cités viennent de resultats.json (base réelle, Swissvotes) ; les
// tableaux de chaque fiche sont générés, seul ce commentaire est rédigé.

#let fiches = (
  // ── Gauche – droite (F1) : État social ──
  "6600": [La troisième tentative en vingt ans de relever l'âge de la retraite des femmes, après l'échec de Prévoyance 2020. Tous les partis bourgeois et le Conseil fédéral pour ; la gauche, les syndicats et les associations féminines contre. Accepté de justesse (50,5 %) grâce à la Suisse alémanique (55 % de oui), alors que la Romandie a dit non à 63 %, et le Jura à 71 %. C'est l'objet le plus net du facteur gauche–droite (−0,91) : la même opposition revient sur tout ce qui touche aux retraites et à la santé, avec une Romandie qui vote à gauche de ses partis.],
  "6760": [Réforme technique du financement de la santé, combattue par le syndicat SSP au nom des patients et du personnel. Le PS national a dit non, mais sept de ses sections cantonales alémaniques ont dit oui. Acceptée à 53,3 %, elle est rejetée en Romandie (37 % de oui) et approuvée en Suisse alémanique (58 %). Son profil est presque celui d'AVS 21 : la géographie du vote suit le Röstigraben de l'État social davantage que les mots d'ordre.],
  "6250": [Loi autorisant les assurances sociales à faire observer les assurés soupçonnés d'abus, adoptée rapidement après un arrêt de la Cour européenne des droits de l'homme (2016). Le référendum est parti d'un comité citoyen sur Internet, soutenu par la gauche et le PVL. Accepté à 64,7 % : Genève a dit non (41 % de oui), Appenzell Rhodes-Intérieures oui à 81 %. L'objet est très bas sur le facteur gauche–droite (−0,85) : une question d'assurances sociales et d'abus, lue selon le même clivage que les retraites.],
  "6590": [Volet financier d'AVS 21 (+0,4 point de TVA), lié à la loi : les deux passaient ou tombaient ensemble. Plus consensuel (55,1 %), il suit pourtant la même géographie, du Jura (38 % de oui) à Zoug (67 %). C'est l'objet le plus bas de l'axe 2 (−0,77) : le camp gouvernemental uni contre la gauche, avec une Romandie qui vote contre les autorités.],
  "6670": [Initiative du PS : aucune famille ne devrait consacrer plus de 10 % de son revenu aux primes d'assurance-maladie. Rejetée à 55,5 %, elle a pourtant été acceptée en Romandie (62 % de oui) et au Tessin (57 %), avec des pointes dans le Jura (72 %) et à Neuchâtel (70 %) ; Appenzell Rhodes-Intérieures n'en voulait qu'à 20 %. Le facteur gauche–droite l'explique presque entièrement (0,94) : c'est le prototype des objets d'État social où la Suisse latine vote à gauche.],
  "6220": [Initiative du syndicat paysan Uniterre, portée surtout en Suisse romande : droits de douane, soutien aux petites exploitations, pas d'OGM. Rejetée à 68 %, elle a été acceptée à Genève (60 %) et dans le canton de Vaud (57 %), alors qu'Obwald ne lui donnait que 16 %. Elle est tout en haut du facteur gauche–droite. Ce n'est pas l'agriculture qui la place là, mais le soutien de la gauche et la géographie romande : l'Union suisse des paysans, elle, ne s'était pas engagée.],
  "6210": [Initiative des Verts pour imposer des normes écologiques et sociales à tous les aliments, importations comprises. Même soir et même géographie que la souveraineté alimentaire : 64 % de oui à Genève et dans le canton de Vaud, 20 % en Obwald. Les initiatives agricoles de 2018 se rangent sur le facteur gauche–droite, celles de 2021-2022 (pesticides, eau potable, élevage) sur le facteur écologique. Les premières opposaient la Romandie à la Suisse alémanique, les secondes les villes aux campagnes.],
  "6650": [Première initiative syndicale sur l'État social acceptée par le peuple et les cantons (58,2 %, 15 cantons sur 23). Tous les partis bourgeois et les milieux économiques s'y opposaient ; les sections UDC de Genève et du Jura ont fait défection, et le oui a largement dépassé l'électorat de gauche. La Romandie a dit oui à 75 %, le Jura à 83 %, et même Zurich et Argovie l'ont acceptée ; Appenzell Rhodes-Intérieures seul l'a nettement rejetée (31 %). Profil typique du facteur gauche–droite (0,88), avec une part d'axe 2 (0,49), celle du vote contre les recommandations des autorités.],

  // ── Ouverture – souverainisme (F2) ──
  "6860": [Initiative de l'UDC : plafonner la population résidente à 10 millions d'ici 2050, quitte à dénoncer la libre circulation. Seule l'UDC la soutenait. Rejetée à 54,8 %, elle a partagé le pays entre villes (33 % de oui) et campagnes (56 %), et entre Bâle-Ville (27 %) et Appenzell Rhodes-Intérieures (66 %). La Romandie l'a rejetée à 62 %, le Tessin l'a acceptée à 51 %. C'est l'objet le plus bas de l'axe 1 (−0,86) et l'un des plus nets du facteur souverainisme (−0,83).],
  "6310": [Nouvelle tentative de l'UDC et de l'ASIN de mettre fin à la libre circulation avec l'UE, six ans après l'initiative « contre l'immigration de masse » (2014, avant la période étudiée). Rejetée à 61,7 %, elle n'a été acceptée qu'à Schwyz, Glaris, Appenzell Rhodes-Intérieures et au Tessin ; Bâle-Ville l'a rejetée à 75 %. Le Tessin (53 % de oui) est la région linguistique la plus favorable. Même profil que « 10 millions » : −0,83 sur le facteur ouverture–souverainisme.],
  "5970": [L'UDC voulait inscrire dans la Constitution une liste d'infractions entraînant l'expulsion automatique, pour contourner la loi d'application de son initiative de 2010, jugée trop douce. Une mobilisation inédite de la société civile, des universitaires aux milieux économiques, l'a fait échouer (41,1 %), avec une participation de 64 %. Le Tessin l'a acceptée (59 %), Bâle-Ville rejetée à 70 %. C'est l'un des pôles du facteur souverainisme (−0,83).],
  "6821": [Initiative du Mouvement suisse pour la liberté : garantir les pièces et les billets dans la Constitution. Le Parlement lui a opposé un contre-projet direct, accepté à 73 %, tandis que l'initiative échouait (45,6 %). Le oui à l'initiative culmine dans le Jura (62 %) et à Neuchâtel (59 %) et reste bas à Bâle-Ville (38 %). C'est l'objet le plus haut de l'axe 2 (0,79) : il réunit contre les autorités des électorats de gauche comme de droite, en périphérie et surtout en Suisse latine.],
  "6790": [Deuxième essai d'identité électronique, émise cette fois par l'État, après le rejet de la version privée en 2021. Tous les partis sauf l'UDC la soutenaient. Le référendum des milieux « libertés » (Amis de la Constitution, Mass-voll, Parti pirate, Jeune UDC) a pourtant failli l'emporter : 50,4 % de oui seulement, 57 % dans les villes et 42 % dans les campagnes. C'est l'objet le plus haut du facteur ouverture (0,87) : l'opposition ouverture–souverainisme y prend la forme d'une confiance ou d'une défiance envers l'État numérique.],
  "6440": [Révision de la loi sur le CO2 pour tenir l'Accord de Paris : taxe sur les billets d'avion, fonds pour le climat. Soutenue par tous les partis sauf l'UDC et par les milieux économiques, elle a été rejetée (48,4 %) par une forte mobilisation rurale, le soir même des initiatives sur les pesticides et l'eau potable : 61 % de oui dans les villes, 37 % dans les campagnes. Facteur ouverture : 0,87. L'écologie « institutionnelle », soutenue par le camp gouvernemental, se range du côté de l'ouverture, pas sur le facteur écologique.],
  "6280": [Reprise de la directive européenne sur les armes, condition du maintien dans Schengen et Dublin. Les tireurs et l'UDC contre, tous les autres pour. Acceptée à 63,7 % ; seul le Tessin l'a rejetée (45,5 % de oui). Comme les lois COVID et l'e-ID, c'est un objet où l'UDC est seule contre tous et où l'enjeu européen se double d'une question de confiance envers les autorités (facteur ouverture : 0,86).],
  "6500": [Deuxième référendum contre la loi COVID, cette fois sur le certificat sanitaire, au plus fort de la contestation des mesures ; la participation a atteint 66 %. Acceptée à 62 %, elle n'a été rejetée qu'à Schwyz et en Appenzell Rhodes-Intérieures. L'UDC, qui avait laissé la liberté de vote en juin, recommandait cette fois le non. Profil presque pur du facteur ouverture (0,80), sans aucune composante gauche–droite (−0,02).],

  // ── Écologie et gauche alternative – bloc bourgeois (F3) ──
  "6110": [Suppression des statuts fiscaux des multinationales, compensée par de nouveaux allègements. Tout le camp bourgeois pour, la gauche et les syndicats contre : rejetée à 59 %, surtout en Suisse alémanique (38 % de oui) et dans le canton de Berne (32 %). Seuls Vaud, Zoug, Nidwald et le Tessin l'ont acceptée. C'est l'objet le plus bas de l'axe 3 (−0,64) : quand la gauche bat le bloc bourgeois uni, c'est grâce aux villes alémaniques et à une partie de l'électorat bourgeois.],
  "6100": [Fonds pour les routes nationales et le trafic d'agglomération, alimenté en partie par une hausse de la surtaxe sur les carburants. Seuls le PS et les Verts recommandaient le non, et trois sections romandes du PS le oui. Accepté à 62 % par tous les cantons, un peu moins dans les villes alémaniques (Bâle-Ville : 54 %). Avec RIE III, il marque le pôle « bloc bourgeois » de l'axe 3 : infrastructures et croissance contre écologie urbaine.],
  "6330": [Hausse de la déduction des frais de garde, élargie par le Parlement à la déduction générale pour enfants, qui profitait surtout aux hauts revenus. Référendum du PS ; rejetée à 63 %. Le Tessin (52 %) et Genève (50 %) sont les plus favorables, les deux Appenzell les moins (28 et 29 %). Sur l'axe 3 (−0,50), elle rejoint les allègements fiscaux défendus par le bloc bourgeois. Son score élevé sur l'axe 1 (0,67) vient de la Suisse latine, plus favorable que la Suisse alémanique à cette aide aux familles.],
  "6530": [Suppression du droit de timbre d'émission sur le capital des entreprises. Référendum de la gauche et des syndicats ; rejetée à 62,6 %, avec une majorité à Zoug seulement (51 %). C'est un objet typique du pôle « bloc bourgeois » de l'axe 3 (−0,50) et du camp gouvernemental sur l'axe 2 (−0,47).],
  "5870": [Initiative de la gauche alternative pour abolir l'imposition d'après la dépense des riches étrangers. Rejetée à 59 %, elle a été massivement repoussée dans les cantons qui en vivent le plus (Valais : 22 % de oui, Grisons : 29 %), et davantage en Romandie (31 %) qu'en Suisse alémanique (44 %). Zurich, qui l'avait déjà abolie chez lui, a voté oui à 49 %, et Schaffhouse l'a acceptée (51 %). C'est l'objet le plus haut de l'axe 3 (0,76) : une redistribution soutenue par les villes alémaniques, pas par la Suisse latine.],
  "6410": [Initiative de l'association de Franziska Herren : plus de paiements directs pour les exploitations qui utilisent des pesticides ou des antibiotiques préventifs. Rejetée à 61 %, lors de la plus forte mobilisation paysanne de la période : 52 % de oui dans les villes, 28 % dans les campagnes, 59 % à Bâle-Ville et 22 % en Valais. C'est un pôle du facteur écologique (0,75). La même association porte l'initiative sur l'alimentation du 27 septembre 2026.],
  "6420": [Interdire en dix ans les pesticides de synthèse dans l'agriculture et dans les aliments importés. Même soir, même résultat (39,4 %) et même géographie que l'eau potable. On attribue souvent aux deux initiatives agricoles la mobilisation rurale qui a fait tomber la loi sur le CO2 le même jour.],
  "6580": [Inscrire dans la Constitution des normes de bien-être animal au niveau du cahier des charges de Bio Suisse, importations comprises. Rejetée à 62,9 % : 49 % de oui dans les villes, 26 % dans les campagnes, de 55 % à Bâle-Ville à 22 % en Appenzell Rhodes-Intérieures. C'est le troisième grand objet du pôle « écologie » de l'axe 3 (0,71).],

  // ── Axes 4 à 6 ──
  "6680": [Initiative du Centre : obliger la Confédération et les cantons à agir si les coûts de la santé augmentent plus vite que les salaires. Seul le Centre la soutenait. Rejetée à 62,8 %, elle a été acceptée dans cinq cantons latins : le Tessin, Fribourg, le Valais, Neuchâtel et le Jura. C'est l'objet le plus haut de l'axe 4 (0,59). Ce score tient au Valais, au Tessin et aux Grisons, où elle a fait mieux que ne le laissaient prévoir les trois premiers axes, sur les terres de l'ancien PDC.],
  "6030": [Loi d'application du diagnostic préimplantatoire, combattue par des milieux conservateurs et évangéliques et par des associations de personnes handicapées. Acceptée à 62,4 %. Le Centre (alors PDC) la soutenait, mais huit de ses sections cantonales, surtout de Suisse centrale et orientale, ont dit non. Genève et Vaud l'ont approuvée à plus de 80 %, les deux Appenzell l'ont rejetée de justesse (49,5 %). Son score négatif sur l'axe 4 (−0,26) traduit une réticence catholique qu'on retrouve sur le mariage pour tous.],
  "6170": [Suppression pure et simple de la redevance radio-TV, lancée par de jeunes libéraux-radicaux et UDC. Rejetée à 71,6 % par tous les cantons, plus nettement encore en Romandie (24 % de oui ; 22 % à Neuchâtel et dans le Jura), qui bénéficie de la répartition de la redevance au sein de la SSR. C'est l'objet le plus bas de l'axe 5 (−0,47) : le Tessin, pourtant bénéficiaire lui aussi, y a été plus favorable que les Grisons romanches.],
  "6320": [Révision permettant de tirer des loups avant qu'ils ne causent des dégâts. Référendum des organisations de protection de la nature ; rejetée par le peuple (48,1 % de oui) alors qu'une majorité de cantons l'approuvait. Elle a obtenu 39 % dans les villes et 59 % dans les campagnes, avec des pointes en montagne (Uri 70 %, Appenzell Rhodes-Intérieures 71 %). C'est l'objet le plus haut de l'axe 5 (0,39) : les Grisons, le Haut-Valais et les régions de montagne s'y distinguent du Tessin.],
  "6720": [Baisse du taux de conversion du 2#super[e] pilier, avec des compensations. Tous les partis bourgeois pour ; la gauche et les syndicats contre, par référendum. Rejetée à 67 % dans tous les cantons, et jusqu'à 77 % dans le Jura. Elle est surtout gauche–droite (facteur F1 : −0,56), mais c'est aussi l'objet le plus haut de l'axe 6 (0,50). Une lecture possible : les communes paysannes de montagne, peu concernées par le 2#super[e] pilier, l'ont moins rejetée que les communes ouvrières du Mittelland.],
  "6450": [Mesures policières préventives contre des « terroristes potentiels », dès 12 ans. Référendum des jeunesses de gauche et vert'libérale et du Parti pirate ; acceptée à 56,6 %. C'est l'objet le plus bas de l'axe 6 (−0,43) : les communes industrielles de Soleure et du Jura bernois l'ont davantage approuvée que ne le prédisaient les trois premiers axes.],

  // ── Les deux extrêmes de l'axe 1 non tourné ──
  "6340": [Deux semaines de congé paternité financées par les APG. Référendum d'élus UDC et de Jeunes libéraux-radicaux. L'UDC et le PLR recommandaient le non, mais huit sections cantonales du PLR, surtout latines, ont dit oui. Accepté à 60,3 %, dont 82 % dans le canton de Vaud et 35 % en Appenzell Rhodes-Intérieures. C'est l'objet le plus haut de l'axe 1 (0,95), celui qui le résume le mieux : une réforme de société que la gauche, le centre et la Suisse latine soutiennent contre la droite alémanique.],
  "6350": [Crédit de six milliards pour de nouveaux avions de combat. Référendum du GSsA, du PS et des Verts ; accepté par 50,1 % seulement. Le Jura (31 %) et Bâle-Ville (37 %) s'y opposaient, Nidwald (66 %) et Schwyz (63 %) le soutenaient. Axe 1 : −0,83. L'armée est l'un des marqueurs les plus nets de l'opposition gauche–droite, et le Röstigraben s'y ajoute (41 % de oui en Romandie).],
)
